FROM node:10.16.0-alpine as builder

WORKDIR /app
COPY ./package.json ./

ENV NODE_ENV=local

RUN npm install
COPY . .

EXPOSE 4200/tcp

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]